[package]
name = "bevy_fast_tilemap"
version = "0.3.0"
edition = "2021"
description = "A GPU accelerated simple tilemap for bevy"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Droggelbecher/bevy-fast-tilemap"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
rand = "0.8.*"
num = "0.4.*"

[dev-dependencies]
bevy-inspector-egui = "0.18.3"

[lib]
name = "bevy_fast_tilemap"
path = "src/lib.rs"
